theme: jekyll-theme-slate
title: Kelvin Cao
description: 
Software & Game Developer, Digital & 3D Artist
<br>
<a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
github:
  is_project_page: false
