theme: jekyll-theme-minimal
title: Kelvin Cao
#logo: 
description: >
  Software & Game Developer
  <br>
  Digital & 3D Artist
  <br>
  <a href="https://www.hackerrank.com/khncao">HackerRank</a>
  <a href="https://www.linkedin.com/in/khncao/">LinkedIn</a>  
  <br><hr>
  <b>Skills</b>
  <br>
  C#, Python, C++, Java, HTML, CSS, JavaScript, SQL,<br>
  Unity Engine, Blender, Django, Git, GitHub, Bitbucket,<br>
  Windows, Linux, Android,<br>
  UI/UX, 3D CG, Illustration, Gaming, Algorithms, Data structures & analysis
  <br><br>
  <b>Goals</b>
  <br>
  CS/STEM Master's, industry experience

show_downloads: false
github:
  is_project_page: false
