theme: minima
title: Kelvin Cao

plugins:
  - jekyll-titles-from-headings

show_downloads: false
github:
  is_project_page: false
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 