theme: jekyll-theme-minimal
title: Kelvin Cao
#logo: 
description: >
  Software & Game Developer
  <br>
  Digital & 3D Artist
  <br>
  <a href="https://www.linkedin.com/in/kelvin-cao-08b88a79/">LinkedIn</a>  <a href="https://stackoverflow.com/users/13619326/khncao">StackOverflow</a>  <a href="https://www.artstation.com/khncao">ArtStation</a> 
show_downloads: false
github:
  is_project_page: false
